
POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Teste normal", 
   "nickname": "NORMAL", 
   "email": "normal@example.com",
   "password": "role123",
   "role": "normal"
}
###

POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email": "normal@example.com",
   "password": "role123"
}

###
PUT http://localhost:3003/user/edit/20bd6989-35f6-46a0-9ee5-caddc4e1b4c0
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIwYmQ2OTg5LTM1ZjYtNDZhMC05ZWU1LWNhZGRjNGUxYjRjMCIsImlhdCI6MTY1NDY0NzU4MSwiZXhwIjoxNjU0NjUxMTgxfQ.QjnFbW9cy_PH9CkJO6clhBaFJq6leqtkW0slrhkrcaI

{
   "name": "Harry Osbourne",
   "nickname": "Harry" 
}

###


GET  http://localhost:3003/user/profile
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MWEyNGU3LWEyZTYtNGE1Zi05N2ViLWMxNzhkNDAwOWEyNCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzU4MDk1MDUsImV4cCI6MTY3NTgxMzEwNX0.Q_5PjWE5W_eDLaOxpva4XFjj7sZlCgC0kOKXKmFwUuY